spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reno
    username: root
    password: 123123

mybatis:
  mapper-locations: classpath*:mapper/*.xml