spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reno?autoReconnect=true
    username: root
    password: 123123

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    pool:
      max-active: 200
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 1000

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  config: classpath:log/logback-spring.xml

